### ISSUE TITLE
Siri Commands

### ISSUE THREAD

**Issue by amitgandhinz** [xfjx/homebridge-wunderground#1]
What are some example Siri commands you use with this?  How do you use this as a trigger for other accessories?

**Comment by amitgandhinz** [comment]
nvm, i labelled the zone backyard (no spaces), and then siri started recognizing the location (as opposed to Back Yard).

**Comment by xfjx** [comment]
Hey amitgandhinz!

Right you can just call the accessory "backyard" or place it in a room and then ask Siri. But all my rooms are just one word (german) so thank you very much for the trick.

For triggers you can not use the accessory as an event but you can use it in the conditions. Let's say you come home and depending on the temperature outside you want  a special scene activated. 

This is my first version and everything might be still buggy or maybe you come up with a feature that would be nice to add so I would really appreciate further feedback. Thank you very much in advance!
