### ISSUE TITLE
customize polling interval

### ISSUE THREAD

**Issue by lyance** [xfjx/homebridge-wunderground#12]
Hi there, just wondering... is there a way to customize the polling interval of the plug-in?  I understand that it polls for new weather data every minute, which means 60x24 requests per day -- exceeding the 500 requests for the free Stratus developer wunderground account.  Thanks a lot, BTW great plug-in!

**Comment by xfjx** [comment]
Hi lyance,

I could change it to 3 minutes by default so one will not run into the 500 calls/day limit.
On the other hand it only get's new data if someone is looking at them like using the home app or asking Siri for something.

Please let me know if you have other findings and think it is possible to run into the limit. 

Hint: you can see if the plugin polled new information in the homebridge log.

**Comment by lyance** [comment]
Thanks for replying, xfjx!  It would be great to let it poll every 3 minutes as long as it doesn't exceed 500 calls/day. I was thinking of using the plugin as a temperature sensor for Homekit automation. It would be great if it can poll for weather data on it's own - even without a user requesting. That would make the automation fully auto. Thanks again!

**Comment by xfjx** [comment]
I changed the default to 3 minutes now.
