### ISSUE TITLE
Runs ok for hours, and then: Error fetching weather data fr om wunderground.com!

### ISSUE THREAD

**Issue by lyance** [xfjx/homebridge-wunderground#13]
Hi xfjx.  I've encountered a strange error while running the plugin after a few hours (prior to which, weather data fetching was OK).  The log shows:  "Error fetching weather data fr om wunderground.com! Check your configuration." Subsequently, this causes the homebridge application abort and exit -- taking down the rest of the homebridge accessories with it.  It seems to be reproducible after every restart of the homebridge -- happens a few hours later.  

More details can be found in this [log file](https://dl.dropboxusercontent.com/u/10110226/wundeground-error.pdf)

Please advise if there's a mistake in my setup.

Thanks and Best Regards.

**Comment by zieherf** [comment]
I get the same response sometimes when requesting weather information from wunderground.com
The `error` object does not exist in all cases (line 41 ver 0.0.3), thus causing an uncaught exception.

In version 0.0.3 you need to change line 41 (line 56 in 0.0.4) from 

`if (response['response']['error']['type'] && response['response']['error']['description']) `
to
`if (response['response']['error'] && response['response']['error']['type'] && response['response']['error']['description'])`

@xfjx could you please look into that -- thanks

**Comment by xfjx** [comment]
Thank you very much @zieherf. I fixed it and pushed an update to github and NPM.

I also changed the update interval to three minutes in order to stop running into the daily limit. 

Maybe you could check here what was the errors you got: http://www.wunderground.com/weather/api There is table of all the errors you got and when and how often.
