### ISSUE TITLE
Polling?

### ISSUE THREAD

**Issue by ToddGreenfield** [xfjx/homebridge-wunderground#16]
Hi - Thanks for the work on this plugin! I have been using it for a while but never really paid attention until now-
I have the Homekit app up on my iPad mini pretty much all day, being used as the home hub, and I display the outside temp on the main page.
What I am noticing is that the temp is not being regularly updated, unless I close the app and reopen to purposely refresh.
I just took a look at the code to see how it was doing its polling- I am not really a js programmer but I do not see where exactly it is polling anything. I can see where it is checking the interval (on line 40), and calling for an update, but not doing any actual polling without user interaction...

My other question/issue, which may be related, is getStateHumidity and getStateTemperature both call getState - where getState is checking the timestamp. So if Humidity and Temp are both queried together, then one probably isn't getting updated appropriately because the other was just called.

Thoughts?

**Comment by xfjx** [comment]
Hi Todd,

currently the data only gets updated when you are looking at it. I will try to switch to timer based update instead. Please give a few days for that.

**Comment by ToddGreenfield** [comment]
Thanks. Let me know if you need help testing.

**Comment by xfjx** [comment]
Thank you very much, Todd. I am really busy right now so I was not able to look into your pull request yet. I will check and merge it in the next days.

**Comment by xfjx** [comment]
I was not able to test your implementation yet. I merged it anyway. 

Thank you very much
