### ISSUE TITLE
Question - Temperature conversion from C to F?

### ISSUE THREAD

**Issue by Tiger519** [xfjx/homebridge-wunderground#18]
I have noticed you are pulling the temp_c value from the response, and the console log shows the temperature in C. Yet in the Home app, it is displaying the temperature in F (which for me is desired!). I'm curious if this is something being done automatically by Homekit? I couldn't see any conversion in the code. I was messing around with a different plugin before I found yours, and was going to try to pull the temp_f value instead of temp_c.

**Comment by xfjx** [comment]
I think homekit or the node module used by homebridge does that.

Good the hear that temperature in F is also working. Have not tried that before.
