### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by samsonrosen** [xfjx/homebridge-wunderground#5]
Hi!

The plugin is great.

Can these be used for automation at all? I seeing the information in HomeKit but it can't be 'acted on'.

Thanks,

Sam

**Comment by samsonrosen** [comment]
I've attached screenshots of what I am referring to.
![img_1382](https://cloud.githubusercontent.com/assets/7211878/21126615/56e866d0-c0e5-11e6-9366-cf2869c0535d.PNG)
![img_1381](https://cloud.githubusercontent.com/assets/7211878/21126616/5844459e-c0e5-11e6-9ab9-289d35fc714f.PNG)

**Comment by xfjx** [comment]
Hi Sam,

I'm afraid you can not use the outside temperature as a trigger. At least not with Apple's Home App. 

There is another app (also called Home) that do it, but I am not sure if they really work.
The problem would be that you can not set a logical condition like greater or lower that X but only equals X and that would be still a problem.

:-(

**Comment by lyance** [comment]
Just FYI: I also encountered the same issue with the iOS Home app. But using another homekit app like Elgato Eve, I'm able to use the plugin as a temperature sensor and use it for automation. Cool!
