### ISSUE TITLE
In correct temperature and humidity.

### ISSUE THREAD

**Issue by cshilton** [xfjx/homebridge-wunderground#6]
I'm using the following config:

"accessories": [ {
  "accessory": "WUNDERGROUND",
  "name": "Weather Underground",
  "device": "KCTMILFO8",
  "key": "<my key>",
  "city": "06461"
} ...

And the plugin only reports -58 degrees and 0% humidity. When I go to http://api.wunderground.com I can see the correct temperature and humidity in the xml retrieved.

**Comment by ToddGreenfield** [comment]
You need to have an appropriate API key. Head over to the weather underground website, sign up for a free account, setup an API, then paste the api key in the "key" of your config like so-
I also use a very nearby weather station code for much more accurate info-
Hope this helps.
    {
      "accessory": "WUNDERGROUND",
      "name": "Weather Underground",
      "device": "WURecklinghausen",
      "key": "xxxxxxxxxxbc81d",
      "city": "pws:KNJ3"
      }

**Comment by xfjx** [comment]
Todd is right, I tried your config with my API key and it works just fine.

Thank you Todd for helping out.
