### ISSUE TITLE
Plugin fails to connect when using systemd setup for Homebridge

### ISSUE THREAD

**Issue by chrisfromthelc** [xfjx/homebridge-wunderground#7]
When using the [systemd setup here](https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/), the WUnderground plugin fails to start/connect to Wunderground.

Reloading the system daemon using `systemctl daemon-reload` seems to revive the plugin, even though Homebridge previously has started successfully after a reboot and works.

The plugin settings are as below (API key obscured, of course).

```
                "accessory": "WUNDERGROUND",
                "name": "Weather",
                "device": "KAZSCOTT236",
                "key": "xxxxxxxxxxxxx0a946",
                "city": "AZ/Scottsdale"
```

Any suggestions/fixes?

**Comment by xfjx** [comment]
That's strange! I'm using my own systemd startup without any problems.

The only thing I can think of: when started through systemd it will use the user homebridge. Do you have a valid config file under /etc/default/homebridge that the user homebridge can read? Maybe you started it as root or another user before where it was working.

Please tell me the exact error message.

systemctl -l status homebridge

You could also try my systemd startup file. This will read the homebridge configuration from /home/homebridge/.homebridge




/usr/lib/systemd/system/homebridge.service
=================================

[Unit]
Description=Homebridge Service
After=network.target

[Service]
ExecStart=/usr/bin/homebridge
Restart=always
RestartSec=5
User=homebridge
Group=homebridge

[Install]
WantedBy=multi-user.target

**Comment by xfjx** [comment]
I added some error handling. Please update and try again and let me know if and what error message you receive.

You can have a look at the error message with 

 # sudo systemctl status -l homebridge
